name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: dnf install -y fennel make

    - name: Run tests
      run: make test
