name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install luarocks
      run: apt install luarocks

    - name: Install fennel
      run: luarocks install fennel

    - name: Run tests
      run: make test
